# Generated by Django 5.1.7 on 2025-03-11 13:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0002_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='mesa',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='precio_base',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='mesa_id',
        ),
        migrations.AddField(
            model_name='pago',
            name='pedido',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='bar.pedido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='bar.producto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='bar.topping'),
        ),
        migrations.DeleteModel(
            name='Mesa',
        ),
    ]
