# Generated by Django 5.1.7 on 2025-03-12 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0003_topping_remove_pedido_mesa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='toppings',
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ventas', to='bar.producto')),
                ('toppings', models.ManyToManyField(blank=True, to='bar.topping')),
            ],
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
